deploy finalpro7

diff --git a/sonarcloud.yml b/sonarcloud.yml
--- a/sonarcloud.yml
+++ b/sonarcloud.yml
@@ -38,18 +38,19 @@ phases:
   build:
     commands:
       - echo "Running Maven SonarCloud analysis..."
-      - mvn sonar:sonar \
-          -Dsonar.login=$SONARCLOUD_TOKEN \
-          -Dsonar.host.url=$HOST \
-          -Dsonar.projectKey=$PROJECTKEY \
-          -Dsonar.organization=$SONARCLOUD_ORG
+      - >
+        mvn sonar:sonar
+        -Dsonar.login=$SONARCLOUD_TOKEN
+        -Dsonar.host.url=$HOST
+        -Dsonar.projectKey=$PROJECTKEY
+        -Dsonar.organization=$SONARCLOUD_ORG
       - echo "SonarCloud analysis completed. Checking Quality Gate status..."
-      - |
-        RESPONSE=$(curl -s -u "$SONARCLOUD_TOKEN:" "$HOST/api/qualitygates/project_status?projectKey=$PROJECTKEY" | jq -r '.projectStatus.status')
-        echo "Quality Gate status: $RESPONSE"
-        if [ "$RESPONSE" != "OK" ]; then 
-          echo "Quality Gate failed."
-          exit 1
+      - >
+        RESPONSE=$(curl -s -u "$SONARCLOUD_TOKEN:" "$HOST/api/qualitygates/project_status?projectKey=$PROJECTKEY" | jq -r '.projectStatus.status');
+        echo "Quality Gate status: $RESPONSE";
+        if [ "$RESPONSE" != "OK" ]; then
+          echo "Quality Gate failed.";
+          exit 1;
         fi
 
 artifacts:
