deploy finalpro5

diff --git a/sonarcloud.yml b/sonarcloud.yml
--- a/sonarcloud.yml
+++ b/sonarcloud.yml
@@ -44,9 +44,13 @@ phases:
             -Dsonar.projectKey=$PROJECTKEY \
             -Dsonar.organization=$SONARCLOUD_ORG
       - echo "SonarCloud analysis completed. Checking Quality Gate status..."
-      - RESPONSE=$(curl -s -u $SONARCLOUD_TOKEN: "$HOST/api/qualitygates/project_status?projectKey=$PROJECTKEY" | jq -r '.projectStatus.status')
+      - RESPONSE=$(curl -s -u "$SONARCLOUD_TOKEN:" "$HOST/api/qualitygates/project_status?projectKey=$PROJECTKEY" | jq -r '.projectStatus.status')
       - echo "Quality Gate status: $RESPONSE"
-      - if [ "$RESPONSE" != "OK" ]; then echo "Quality Gate failed."; exit 1; fi
+      - |
+        if [ "$RESPONSE" != "OK" ]; then 
+          echo "Quality Gate failed."
+          exit 1
+        fi
 
 artifacts:
   files:
